export interface Work {
  assets?: [];
  author_avatar?: string;
  author_id?: number;
  author_name?: string;
  category?: number;
  collect_count?: number;
  comment_areaid?: number;
  comment_count?: number;
  copyright?: number;
  cover?: string;
  description?: string;
  file?: string;
  file_data?: string;
  file_size?: number;
  follow_state?: number;
  goods_list?: any[];
  id?: number;
  is_collect?: number;
  is_like?: number;
  like_count?: number;
  name?: string;
  publishtime?: string;
  share_count?: number;
  tag?: [];
  updatetime?: string;
  cooperateid?: number;
  authority?: number[];
}
